---
default_stages:
  - pre-commit
fail_fast: false
minimum_pre_commit_version: 2.15.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      # Git hooks
      - id: check-added-large-files
        args:
          - --maxkb=2000
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-submodules
      - id: no-commit-to-branch
        args:
          - --branch
          - master

      # Common errors
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md,markdown,mdown,mkd"

      # JSON
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-ensure-ascii

      # Cross platform
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: destroyed-symlinks
      - id: mixed-line-ending
        args:
          - --fix=lf

      # Security
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

      # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
        args:
          - --django
      - id: requirements-txt-fixer

  # Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: c0f51014b8ec51c4455a7dac40697be15e285668 # v1.99.5
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-diff
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=SPECS.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  - repo: local
    hooks:
      - id: tfsort
        name: tfsort
        entry: hooks/tfsort.sh
        language: script
        types:
          - terraform

  # Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: c7acf33d962e8effc070072f993c365af19e3661 # v8.27.2
    hooks:
      - id: gitleaks

  # YAML
  - repo: https://github.com/google/yamlfmt
    rev: 398e72ad8473251b65d9da2cbd43a4b92a61fab7 # v0.17.2
    hooks:
      - id: yamlfmt

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=.yamllint.yml
